import asyncio

from typing import ClassVar, Optional

from caligo import command, module


class Profiles(module.Module):
    name: ClassVar[str] = "Funny"

    @command.desc("Send an animated 'Menyala abangku🔥🙌' message")
    @command.usage(
        ".menyala"
    )
    @command.alias("ma", "padi")
    async def cmd_menyala(self, ctx: command.Context):  
        await ctx.respond("tipis tipis cakk 🔥🔥")
        await asyncio.sleep(1.1)
        await ctx.respond("sesekali 🙌🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("kelas abangkuu 🔥🔝")
        await asyncio.sleep(1.1)
        await ctx.respond("izin abangkuu 🔥")
        await asyncio.sleep(1.1)
        await ctx.respond("panutan 🔝✊🏼🙌🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("kelas abangda 🔥🫡")
        await asyncio.sleep(1.1)
        await ctx.respond("rispeekk 👍🏼🙌🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("manyala ilmu padi 🌾")
        await asyncio.sleep(1.1)
        await ctx.respond("kelas boskuuuh 🔥👍🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("kalau diatas jgn lupa merunduk")
        await asyncio.sleep(1.1)
        await ctx.respond("tetep ilmu padi 🌾🌾")
        await asyncio.sleep(1.1)
        await ctx.respond("kasih paham tipis tipis 🤝🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("top abangku 👍🏼👍🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("eh yg punya setengah indo nih ee 😜😜")
        await asyncio.sleep(1.1)
        await ctx.respond("kelas banget kanda 🙏🏼🕺🏻")
        await asyncio.sleep(1.1)
        await ctx.respond("manyala capt 🔥🔥")
        await asyncio.sleep(1.1)
        await ctx.respond("abang idola panutan ini 😘😘")
        await asyncio.sleep(1.1)
        await ctx.respond("top 🔝 jangan kasih kendor ee 🕺🏻🕺")
        await asyncio.sleep(1.1)
        await ctx.respond("idola 🙌🏼🙌🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("capt idolaa 🔥🙌🏼🔝")
        await asyncio.sleep(1.1)
        await ctx.respond("kasih paham capt 🔥💯🙌🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("apotik tutup captain 🔥🔥💯🔝")
        await asyncio.sleep(1.1)
        await ctx.respond("lanjutkan abangkuuhh 🔥🔝💥")
        await asyncio.sleep(1.1)
        await ctx.respond("jangan kasi longgar king 🔝💯🔥🙌🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("eitsss pondasi bangsa abangkuuhh 🔥🔝🙌🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("tipis tipis 🔥🔛🔝")
        await asyncio.sleep(1.1)
        await ctx.respond("sesekali 🙌🏼")
        await asyncio.sleep(1.1)
        await ctx.respond("meroket abangku 🚀🚀🚀")
        await asyncio.sleep(1.1)
        await ctx.respond("eihhh mantaapp pedii kaliii 🔥🔥🔥")
        await asyncio.sleep(1.1)
        await ctx.respond("trcium aroma ilmu padi abangkuh🔥🔥🌾🌾 kasih tahu")
        await asyncio.sleep(1.1)
        await ctx.respond("abangkuuu🔥🔥🙇‍♂️🙇‍♂️")
        await asyncio.sleep(1.1)
        await ctx.respond("percaya proses king 💯💯💪❤️‍🔥")
        await asyncio.sleep(1.1)
        await ctx.respond("kelas abangda 🔥🫡")
        await asyncio.sleep(1.1)
        await ctx.respond("capt idolaa 🔥🙌🏼🔝")
        await asyncio.sleep(1.1)
        await ctx.respond("wanita mana yang berani menyakitimu king 💯💯💪❤️‍🔥")
        await asyncio.sleep(1.1)

        return f"Menyala abangku🔥🙌"

